import { NextResponse } from 'next/server'
import { revalidatePath } from 'next/cache'
import { adminContext,audit,jsonError } from '../../../../lib/admin/salon-api'
import { guardMutationRequest } from '../../../../lib/security/request-guards'
const clean=(body)=>({name:String(body.name||'').trim().slice(0,160),price:Math.max(0,Number(body.price)||0),time:Math.max(15,Number(body.durationMinutes)||60),duration_minutes:Math.max(15,Number(body.durationMinutes)||60),category:String(body.category||'Haircut').trim().slice(0,80),description:String(body.description||'').trim().slice(0,1200),enabled:body.published!==false,published:body.published!==false,sort_order:Number(body.sortOrder)||0})
export async function GET(){const context=await adminContext();if(context.response)return context.response;const {data,error}=await context.db.from('services').select('*, staff_services(staff_id)').order('sort_order');return error?jsonError(error):NextResponse.json({services:data||[]})}
const saveService=async(context,body,id=null)=>{const row=clean(body);const staffIds=Array.isArray(body.staffIds)?body.staffIds.map(Number):[];if(row.name.length<2||staffIds.some(value=>!Number.isSafeInteger(value)||value<1)||new Set(staffIds).size!==staffIds.length)return {error:'Invalid service.',status:400};const {data,error}=await context.db.rpc('admin_save_service',{p_actor_id:context.auth.user.id,p_service_id:id,p_name:row.name,p_price:row.price,p_duration:row.duration_minutes,p_category:row.category,p_description:row.description,p_published:row.published,p_sort_order:row.sort_order,p_staff_ids:staffIds});return error?{error,status:400}:{data}}
export async function POST(request){const guard=await guardMutationRequest(request,{rateLimit:{scope:'admin.services',limit:30,windowMs:60_000}});if(guard)return guard;const context=await adminContext();if(context.response)return context.response;const saved=await saveService(context,await request.json());if(saved.error)return jsonError(saved.error,saved.status);revalidatePath('/');revalidatePath('/services');revalidatePath('/booking');return NextResponse.json({service:saved.data},{status:201})}
export async function PATCH(request){const guard=await guardMutationRequest(request,{rateLimit:{scope:'admin.services',limit:30,windowMs:60_000}});if(guard)return guard;const context=await adminContext();if(context.response)return context.response;const body=await request.json(),id=Number(body.id);if(!Number.isSafeInteger(id))return jsonError('Invalid service.',400);const saved=await saveService(context,body,id);if(saved.error)return jsonError(saved.error,saved.status);revalidatePath('/');revalidatePath('/services');revalidatePath('/booking');return NextResponse.json({service:saved.data})}
export async function DELETE(request){const guard=await guardMutationRequest(request);if(guard)return guard;const context=await adminContext();if(context.response)return context.response;const id=Number(new URL(request.url).searchParams.get('id'));if(!Number.isSafeInteger(id))return jsonError('Invalid service.',400);const {error}=await context.db.from('services').delete().eq('id',id);if(error)return jsonError(error);await audit(context.db,context.auth.user,'service.delete','services',id);return NextResponse.json({success:true})}
