import { NextResponse } from 'next/server'
import { revalidatePath } from 'next/cache'
import { adminContext,audit,jsonError } from '../../../../lib/admin/salon-api'
import { guardMutationRequest } from '../../../../lib/security/request-guards'
const clean=(body)=>({name:String(body.name||'').trim().slice(0,160),price:Math.max(0,Number(body.price)||0),time:Math.max(15,Number(body.durationMinutes)||60),duration_minutes:Math.max(15,Number(body.durationMinutes)||60),category:String(body.category||'Haircut').trim().slice(0,80),description:String(body.description||'').trim().slice(0,1200),enabled:body.published!==false,published:body.published!==false,sort_order:Number(body.sortOrder)||0})
export async function GET(){const context=await adminContext();if(context.response)return context.response;const {data,error}=await context.db.from('services').select('*').order('sort_order');return error?jsonError(error):NextResponse.json({services:data||[]})}
export async function POST(request){const guard=await guardMutationRequest(request,{rateLimit:{scope:'admin.services',limit:30,windowMs:60_000}});if(guard)return guard;const context=await adminContext();if(context.response)return context.response;const row=clean(await request.json());if(row.name.length<2)return jsonError('Service name is required.',400);const {data,error}=await context.db.from('services').insert(row).select().single();if(error)return jsonError(error);await audit(context.db,context.auth.user,'service.create','services',data.id);revalidatePath('/');revalidatePath('/services');revalidatePath('/booking');return NextResponse.json({service:data},{status:201})}
export async function PATCH(request){const guard=await guardMutationRequest(request);if(guard)return guard;const context=await adminContext();if(context.response)return context.response;const body=await request.json(),id=Number(body.id),row=clean(body);if(!Number.isSafeInteger(id)||row.name.length<2)return jsonError('Invalid service.',400);const {data,error}=await context.db.from('services').update(row).eq('id',id).select().single();if(error)return jsonError(error);await audit(context.db,context.auth.user,'service.update','services',id);revalidatePath('/');revalidatePath('/services');revalidatePath('/booking');return NextResponse.json({service:data})}
export async function DELETE(request){const guard=await guardMutationRequest(request);if(guard)return guard;const context=await adminContext();if(context.response)return context.response;const id=Number(new URL(request.url).searchParams.get('id'));if(!Number.isSafeInteger(id))return jsonError('Invalid service.',400);const {error}=await context.db.from('services').delete().eq('id',id);if(error)return jsonError(error);await audit(context.db,context.auth.user,'service.delete','services',id);return NextResponse.json({success:true})}
