'use client'
import { useCallback,useEffect,useState } from 'react'

const api=async(url,options={})=>{const response=await fetch(url,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(options.headers||{})}});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Request failed.');return payload}
const useResource=(path,key)=>{const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{setRows((await api(path))[key]||[])}catch(e){setError(e.message)}finally{setLoading(false)}},[path,key]);useEffect(()=>{load()},[load]);return{rows,setRows,loading,error,load}}
const State=({loading,error,children})=>loading?<p>Loading…</p>:error?<p role="alert" className="salon-error">{error}</p>:children
const Button=({children,...props})=><button className="admin-action" {...props}>{children}</button>

export function AppointmentsModule(){const r=useResource('/api/admin/appointments','appointments'),update=async(row,status)=>{await api('/api/admin/appointments',{method:'PATCH',body:JSON.stringify({id:row.id,status,adminNotes:row.admin_notes||''})});r.load()};return <Module title="Appointments" intro="Confirm, complete, cancel or mark client appointments as no-show."><State {...r}><div className="admin-list">{r.rows.map(row=><article key={row.id}><div><strong>{row.reference} · {row.customer_name}</strong><p>{new Date(row.starts_at).toLocaleString('en-GB',{timeZone:'Europe/London'})} · {row.services?.name}</p><p>{row.customer_phone} {row.customer_email||''}</p></div><div><span className={`status ${row.status}`}>{row.status}</span>{['confirmed','completed','cancelled','no_show'].map(status=><Button key={status} onClick={()=>update(row,status)}>{status}</Button>)}</div></article>)}</div></State></Module>}

const emptyService={name:'',price:0,durationMinutes:60,category:'Haircut',description:'',published:true,sortOrder:0}
export function ServicesModule(){const r=useResource('/api/admin/services','services'),[draft,setDraft]=useState(emptyService),[editing,setEditing]=useState(null),save=async(event)=>{event.preventDefault();await api('/api/admin/services',{method:editing?'PATCH':'POST',body:JSON.stringify(editing?{...draft,id:editing}:draft)});setDraft(emptyService);setEditing(null);r.load()},edit=row=>{setEditing(row.id);setDraft({name:row.name,price:row.price,durationMinutes:row.duration_minutes,category:row.category,description:row.description||'',published:row.published,sortOrder:row.sort_order})},toggle=async(row)=>{await api('/api/admin/services',{method:'PATCH',body:JSON.stringify({id:row.id,name:row.name,price:row.price,durationMinutes:row.duration_minutes,category:row.category,description:row.description,published:!row.published,sortOrder:row.sort_order})});r.load()};return <Module title="Services & prices" intro="Add or edit the public menu, guide price, duration and publication state."><form className="admin-inline-form" onSubmit={save}><input aria-label="Service name" placeholder="Service name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/><input aria-label="Price in pence" type="number" min="0" value={draft.price} onChange={e=>setDraft({...draft,price:Number(e.target.value)})}/><input aria-label="Duration" type="number" min="15" value={draft.durationMinutes} onChange={e=>setDraft({...draft,durationMinutes:Number(e.target.value)})}/><input aria-label="Category" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/><input aria-label="Description" placeholder="Description" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/><Button>{editing?'Save changes':'Add service'}</Button>{editing?<Button type="button" onClick={()=>{setEditing(null);setDraft(emptyService)}}>Cancel</Button>:null}</form><State {...r}><div className="admin-list">{r.rows.map(row=><article key={row.id}><div><strong>{row.name}</strong><p>{row.category} · £{(row.price/100).toFixed(2)} · {row.duration_minutes} min</p></div><div><Button onClick={()=>edit(row)}>Edit</Button><Button onClick={()=>toggle(row)}>{row.published?'Unpublish':'Publish'}</Button></div></article>)}</div></State></Module>}

export function ScheduleModule(){const [hours,setHours]=useState([]),[blocked,setBlocked]=useState([]),[error,setError]=useState(''),load=async()=>{try{const data=await api('/api/admin/schedule');setHours(data.hours);setBlocked(data.blockedDates)}catch(e){setError(e.message)}};useEffect(()=>{load()},[]);const save=async()=>{await api('/api/admin/schedule',{method:'POST',body:JSON.stringify({type:'hours',hours})});load()},block=async(event)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));await api('/api/admin/schedule',{method:'POST',body:JSON.stringify(data)});event.currentTarget.reset();load()};return <Module title="Schedule" intro="Set weekly opening hours and exceptional closed dates.">{error?<p className="salon-error">{error}</p>:null}<div className="hours-grid">{hours.map((row,index)=><label key={row.weekday}><span>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][row.weekday]}</span><input type="checkbox" checked={row.is_open} onChange={e=>setHours(hours.map((item,i)=>i===index?{...item,is_open:e.target.checked}:item))}/><input type="time" disabled={!row.is_open} value={row.opens_at?.slice(0,5)||''} onChange={e=>setHours(hours.map((item,i)=>i===index?{...item,opens_at:e.target.value}:item))}/><input type="time" disabled={!row.is_open} value={row.closes_at?.slice(0,5)||''} onChange={e=>setHours(hours.map((item,i)=>i===index?{...item,closes_at:e.target.value}:item))}/></label>)}</div><Button onClick={save}>Save weekly hours</Button><form className="admin-inline-form" onSubmit={block}><input type="date" name="startsOn" required/><input type="date" name="endsOn" required/><input name="reason" placeholder="Closure reason"/><Button>Add closure</Button></form><div className="admin-list">{blocked.map(row=><article key={row.id}><span>{row.starts_on} – {row.ends_on} · {row.reason}</span><Button onClick={async()=>{await api(`/api/admin/schedule?id=${row.id}`,{method:'DELETE'});load()}}>Remove</Button></article>)}</div></Module>}

export function GalleryModule(){const r=useResource('/api/admin/gallery','images'),upload=async(event)=>{event.preventDefault();await api('/api/admin/gallery',{method:'POST',body:new FormData(event.currentTarget)});event.currentTarget.reset();r.load()},src=row=>row.storage_path.startsWith('local/')?`/gallery/${row.storage_path.slice(6)}`:`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/salon-gallery/${row.storage_path}`;return <Module title="Gallery" intro="Upload, caption, publish and remove images."><form className="admin-inline-form" onSubmit={upload}><input type="file" name="file" accept="image/jpeg,image/png,image/webp" required/><input name="altText" placeholder="Accessible image description" required/><input name="caption" placeholder="Caption"/><Button>Upload</Button></form><State {...r}><div className="admin-gallery-list">{r.rows.map(row=><article key={row.id}><img src={src(row)} alt={row.alt_text}/><strong>{row.caption||row.alt_text}</strong><Button onClick={async()=>{if(confirm('Delete this image?')){await api(`/api/admin/gallery?id=${row.id}`,{method:'DELETE'});r.load()}}}>Delete</Button></article>)}</div></State></Module>}

export function SiteContentModule(){const [data,setData]=useState(null),[message,setMessage]=useState('');useEffect(()=>{api('/api/admin/site-content').then(row=>setData(row.content.data))},[]);if(!data)return <Module title="Site content"><p>Loading…</p></Module>;const contact=data.contact||{},identity=data.identity||{},field=(group,key,value)=>setData({...data,[group]:{...(data[group]||{}),[key]:value}});return <Module title="Site content" intro="Edit the public identity, homepage message and contact details."><form className="admin-content-form" onSubmit={async e=>{e.preventDefault();await api('/api/admin/site-content',{method:'PATCH',body:JSON.stringify({data})});setMessage('Saved and published.')}}><label>Salon name<input value={identity.name||''} onChange={e=>field('identity','name',e.target.value)}/></label><label>Hero title<input value={identity.heroTitle||''} onChange={e=>field('identity','heroTitle',e.target.value)}/></label><label>Hero description<input value={identity.heroBody||''} onChange={e=>field('identity','heroBody',e.target.value)}/></label><label>WhatsApp<input value={contact.whatsapp||''} onChange={e=>field('contact','whatsapp',e.target.value)}/></label><label>Email<input value={contact.email||''} onChange={e=>field('contact','email',e.target.value)}/></label><label>Instagram<input value={contact.instagram||''} onChange={e=>field('contact','instagram',e.target.value)}/></label><label>Area<input value={contact.area||''} onChange={e=>field('contact','area',e.target.value)}/></label><label>Address note<input value={contact.addressNote||''} onChange={e=>field('contact','addressNote',e.target.value)}/></label><label>Booking message<input value={data.bookingNotice||''} onChange={e=>setData({...data,bookingNotice:e.target.value})}/></label><Button>Save content</Button>{message?<span>{message}</span>:null}</form></Module>}

export function AdministratorsModule(){const r=useResource('/api/admin/administrators','administrators'),add=async(event)=>{event.preventDefault();const email=new FormData(event.currentTarget).get('email');await api('/api/admin/administrators',{method:'POST',body:JSON.stringify({email})});event.currentTarget.reset();r.load()};return <Module title="Administrators" intro="Invite administrators and revoke access. The final active administrator is protected."><form className="admin-inline-form" onSubmit={add}><input type="email" name="email" placeholder="admin@example.com" required/><Button>Invite administrator</Button></form><State {...r}><div className="admin-list">{r.rows.map(row=><article key={row.user_id}><div><strong>{row.email||row.user_id}</strong><p>{row.is_active?'Active':'Inactive'}</p></div><Button onClick={async()=>{await api('/api/admin/administrators',{method:'PATCH',body:JSON.stringify({userId:row.user_id,isActive:!row.is_active})});r.load()}}>{row.is_active?'Revoke':'Restore'}</Button></article>)}</div></State></Module>}

function Module({title,intro,children}){return <div className="admin-module"><header><h2>{title}</h2>{intro?<p>{intro}</p>:null}</header>{children}</div>}
