'use client'
import { useEffect, useRef, useState } from 'react'
import { adminApi, Feedback, Module, SaveButton, Status, useAdminRows, useSave } from './admin-module-ui'
import { createCustomerDetailController } from './customer-detail-controller'
export default function CustomersModule() { const resource = useAdminRows('/api/admin/customers', 'customers'); const save = useSave(); const [detailState, setDetailState] = useState({ detail: null, loading: false, error: '', draftCustomerId: null }); const [reason, setReason] = useState(''); const [delta, setDelta] = useState(0); const controller = useRef(null); const detail = detailState.detail; const redemptions = detail?.customer_packages?.flatMap(item => item.package_redemptions || []) || []
  if (!controller.current) controller.current = createCustomerDetailController({ load: async (id, signal) => (await adminApi(`/api/admin/customers/${id}`, { signal })).customer, publish: state => setDetailState(state) })
  useEffect(() => () => controller.current?.dispose(), [])
  const loadDetail = async id => { setReason(''); setDelta(0); await controller.current.select(id) }
  const adjust = async customerPackageId => { const customerId = detail?.id; const ok = await save.submit(() => adminApi(`/api/admin/customer-packages/${customerPackageId}`, { method: 'PATCH', body: JSON.stringify({ adjustment: delta, reason }) }), '已記錄調整。'); if (ok && customerId && controller.current.isCurrent(customerId)) { setReason(''); setDelta(0); loadDetail(customerId) } }
  return <Module title="客戶記錄" intro="查看預約、套票、兌換及經審計的餘額調整。"><Feedback {...save}/><Status {...resource}><div className="admin-list">{resource.rows.map(customer => <article key={customer.id}><div><strong>{customer.name}</strong><p>{customer.phone}</p></div><button type="button" onClick={() => loadDetail(customer.id)}>詳情</button></article>)}</div></Status>{detail ? <section><h3>{detail.name} 的記錄</h3><h4>套票及兌換</h4>{detail.customer_packages?.map(item => <article key={item.id}><strong>{item.packages?.name}</strong><p>餘額：{item.sessions_remaining} / {item.total_sessions}</p><label>調整次數<input type="number" value={delta} onChange={e => setDelta(Number(e.target.value))}/></label><label>調整原因（必填）<input value={reason} onChange={e => setReason(e.target.value)} required/></label><SaveButton pending={save.pending} disabled={!reason.trim() || !delta} onClick={() => adjust(item.id)}>儲存調整</SaveButton></article>)}<h4>預約</h4>{detail.appointments?.map(row => <p key={row.id}>{row.reference} · {row.status}</p>)}<h4>兌換記錄</h4>{redemptions.map(row => <p key={row.id}>{row.redeemed_at}</p>)}</section> : null}</Module> }
