'use client'
import { useEffect, useState } from 'react'
import { adminApi, Feedback, Module, SaveButton, useSave } from './admin-module-ui'

export function ScheduleModule() { const save = useSave(); const [hours, setHours] = useState([]); useEffect(() => { adminApi('/api/admin/schedule').then(data => setHours(data.hours || [])).catch(error => save.submit(() => Promise.reject(error))) }, [])
  return <Module title="營業時間" intro="設定每週開放時間。"><div className="hours-grid">{hours.map((row, index) => <label key={row.weekday}>星期{['日','一','二','三','四','五','六'][row.weekday]}<input type="checkbox" checked={row.is_open} onChange={e => setHours(hours.map((item, i) => i === index ? { ...item, is_open: e.target.checked } : item))}/><input type="time" disabled={!row.is_open} value={row.opens_at?.slice(0, 5) || ''} onChange={e => setHours(hours.map((item, i) => i === index ? { ...item, opens_at: e.target.value } : item))}/><input type="time" disabled={!row.is_open} value={row.closes_at?.slice(0, 5) || ''} onChange={e => setHours(hours.map((item, i) => i === index ? { ...item, closes_at: e.target.value } : item))}/></label>)}</div><SaveButton pending={save.pending} onClick={() => save.submit(() => adminApi('/api/admin/schedule', { method: 'POST', body: JSON.stringify({ type: 'hours', hours }) }), '已儲存營業時間。')}>儲存營業時間</SaveButton><Feedback {...save}/></Module> }

export function GalleryModule() { const save = useSave(); const [images, setImages] = useState([]); const load = () => adminApi('/api/admin/gallery').then(data => setImages(data.images || [])).catch(error => save.submit(() => Promise.reject(error))); useEffect(() => { load() }, [])
 return <Module title="圖庫" intro="上載及管理公開圖片。"><form onSubmit={async event => { event.preventDefault(); const ok = await save.submit(() => adminApi('/api/admin/gallery', { method: 'POST', body: new FormData(event.currentTarget) }), '圖片已上載。'); if (ok) { event.currentTarget.reset(); load() } }}><input type="file" name="file" accept="image/jpeg,image/png,image/webp" required/><input name="altText" placeholder="圖片說明" required/><SaveButton pending={save.pending}>上載圖片</SaveButton></form><Feedback {...save}/><div className="admin-gallery-list">{images.map(image => <article key={image.id}><strong>{image.alt_text}</strong><button type="button" onClick={async () => { const ok = await save.submit(() => adminApi(`/api/admin/gallery?id=${image.id}`, { method: 'DELETE' }), '圖片已移除。'); if (ok) load() }}>移除</button></article>)}</div></Module> }
