'use client'
import { useEffect, useRef, useState } from 'react'
import { adminApi, Feedback, Module, SaveButton, Status, useAdminRows, useSave } from './admin-module-ui'
import { createMappingLoadController } from './mapping-load-controller'
import { fromHkdInput, toHkdInput } from './price-hkd'
const blank = { name: '', price: 0, durationMinutes: 60, category: '護理', description: '', published: true, sortOrder: 0, staffIds: [] }
export default function ServicesModule() {
  const resource = useAdminRows('/api/admin/services', 'services'); const save = useSave(); const [draft, setDraft] = useState(blank); const [editing, setEditing] = useState(null); const [mapping, setMapping] = useState({ loading: true, error: '', rows: [], ready: false }); const mappingController = useRef(null)
  if (!mappingController.current) mappingController.current = createMappingLoadController({ load: async signal => (await adminApi('/api/admin/staff', { signal })).staff || [], publish: setMapping })
  useEffect(() => { mappingController.current.reload(); return () => mappingController.current?.dispose() }, [])
  const submit = async (event) => { event.preventDefault(); if (!mapping.ready) return; const ok = await save.submit(() => adminApi('/api/admin/services', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(editing ? { ...draft, id: editing } : draft) })); if (ok) { setDraft(blank); setEditing(null); resource.load() } }
  return <Module title="服務及定價" intro="以港幣管理服務、時長及可提供服務的員工。">{mapping.loading ? <p role="status">載入合資格員工中…</p> : null}{mapping.error ? <p role="alert" className="salon-error">{mapping.error} <button type="button" onClick={() => mappingController.current.reload()}>重試</button></p> : null}<form className="admin-inline-form" onSubmit={submit}><input aria-label="服務名稱" value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} required/><input aria-label="HK$ 價格" type="number" min="0" step="0.01" value={toHkdInput(draft.price)} onChange={e => { const price = fromHkdInput(e.target.value); setDraft({ ...draft, price: price ?? draft.price }) }}/><input aria-label="時長（分鐘）" type="number" min="15" value={draft.durationMinutes} onChange={e => setDraft({ ...draft, durationMinutes: Number(e.target.value) })}/><input aria-label="類別" value={draft.category} onChange={e => setDraft({ ...draft, category: e.target.value })}/><fieldset><legend>合資格員工</legend>{mapping.rows.map(row => <label key={row.id}><input type="checkbox" checked={draft.staffIds.includes(row.id)} onChange={e => setDraft({ ...draft, staffIds: e.target.checked ? [...draft.staffIds, row.id] : draft.staffIds.filter(id => id !== row.id) })}/>{row.display_name || row.name}</label>)}</fieldset><SaveButton pending={save.pending} disabled={!mapping.ready}>{editing ? '儲存更改' : '新增服務'}</SaveButton>{editing ? <button type="button" onClick={() => { setEditing(null); setDraft(blank) }}>取消</button> : null}</form><Feedback {...save}/><Status {...resource}><div className="admin-list">{resource.rows.map(row => <article key={row.id}><div><strong>{row.name}</strong><p>HK${toHkdInput(row.price)} · {row.duration_minutes} 分鐘</p></div><button type="button" onClick={() => { setEditing(row.id); setDraft({ name: row.name, price: row.price, durationMinutes: row.duration_minutes, category: row.category, description: row.description || '', published: row.published, sortOrder: row.sort_order, staffIds: row.staff_services?.map(link => link.staff_id) || [] }) }}>編輯</button></article>)}</div></Status></Module>
}
