'use client'

import { useEffect, useState } from 'react'
import StaffHoursEditor from './StaffHoursEditor'
import TimeOffEditor from './TimeOffEditor'

const blank = { name: '', displayName: '', bio: '', colourHex: '#a98152', isActive: true, sortOrder: 0, serviceIds: [] }

export default function StaffModule() {
  const [staff, setStaff] = useState([]), [services, setServices] = useState([]), [selected, setSelected] = useState(null)
  const [draft, setDraft] = useState(blank), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const load = async () => { setLoading(true); setError(''); try { const [people, items] = await Promise.all([fetch('/api/admin/staff'), fetch('/api/admin/services')]); const [peopleData, itemData] = await Promise.all([people.json(), items.json()]); if (!people.ok) throw new Error(peopleData.error || '未能載入員工。'); if (!items.ok) throw new Error(itemData.error || '未能載入服務。'); setStaff(peopleData.staff || []); setServices(itemData.services || []) } catch (cause) { setError(cause.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const edit = row => { setSelected(row); setDraft({ ...row, bio: row.bio || '', serviceIds: row.serviceIds || [] }) }
  const save = async event => { event.preventDefault(); setError(''); const method = selected ? 'PATCH' : 'POST'; const url = selected ? `/api/admin/staff/${selected.id}` : '/api/admin/staff'; const payload = { name: draft.name, displayName: draft.displayName, bio: draft.bio, colourHex: draft.colourHex, isActive: draft.isActive, sortOrder: draft.sortOrder, serviceIds: draft.serviceIds }; try { const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || '未能儲存員工。'); setDraft(blank); setSelected(null); load() } catch (cause) { setError(cause.message) } }
  const toggleService = id => setDraft(current => ({ ...current, serviceIds: current.serviceIds.includes(id) ? current.serviceIds.filter(value => value !== id) : [...current.serviceIds, id] }))
  return <section className="admin-module" aria-labelledby="staff-title"><header><h2 id="staff-title">員工及排班</h2><p>設定可提供的服務、每週工時及不可預約時間。</p></header>{error ? <p role="alert" className="salon-error">{error}</p> : null}<form className="staff-form" onSubmit={save}><label>姓名<input value={draft.name} onChange={event => setDraft(value => ({ ...value, name: event.target.value }))} required /></label><label>顯示名稱<input value={draft.displayName} onChange={event => setDraft(value => ({ ...value, displayName: event.target.value }))} required /></label><label>排序<input type="number" value={draft.sortOrder} onChange={event => setDraft(value => ({ ...value, sortOrder: Number(event.target.value) }))} /></label><label>顏色<input type="color" value={draft.colourHex} onChange={event => setDraft(value => ({ ...value, colourHex: event.target.value }))} /></label><label className="staff-form-wide">簡介<textarea value={draft.bio} onChange={event => setDraft(value => ({ ...value, bio: event.target.value }))} /></label><fieldset className="staff-form-wide"><legend>可提供服務</legend>{services.map(service => <label key={service.id}><input type="checkbox" checked={draft.serviceIds.includes(service.id)} onChange={() => toggleService(service.id)} />{service.name}</label>)}</fieldset><button className="admin-action">{selected ? '儲存員工' : '新增員工'}</button>{selected ? <button className="admin-action" type="button" onClick={() => { setSelected(null); setDraft(blank) }}>取消編輯</button> : null}</form>{loading ? <p aria-busy="true">正在載入員工…</p> : <ul className="staff-list">{staff.map(row => <li key={row.id}><button type="button" className={selected?.id === row.id ? 'active' : ''} onClick={() => edit(row)}><strong>{row.displayName}</strong><span>{row.isActive ? '啟用' : '停用'} · {row.serviceIds.length} 項服務</span></button></li>)}</ul>}{selected ? <div className="staff-editors"><StaffHoursEditor key={`hours-${selected.id}`} staffId={selected.id} /><TimeOffEditor key={`time-off-${selected.id}`} staffId={selected.id} /></div> : <p className="admin-empty">選擇一位員工以管理工時及休假。</p>}</section>
}
