-- Focused Salon Poke Bristol schema layered on the original reusable platform.
-- Booking display and availability use Europe/London; timestamps remain UTC.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  phone text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.admin_users (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price integer NOT NULL DEFAULT 0 CHECK (price >= 0),
  time integer NOT NULL DEFAULT 60,
  duration_minutes integer NOT NULL DEFAULT 60 CHECK (duration_minutes > 0),
  category text NOT NULL DEFAULT 'Haircut',
  description text,
  enabled boolean NOT NULL DEFAULT true,
  published boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.services ADD COLUMN IF NOT EXISTS duration_minutes integer;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS published boolean NOT NULL DEFAULT true;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
UPDATE public.services SET duration_minutes = COALESCE(duration_minutes, time, 60);
ALTER TABLE public.services ALTER COLUMN duration_minutes SET DEFAULT 60;
DO $$ BEGIN
  ALTER TABLE public.services ADD CONSTRAINT services_duration_positive CHECK (duration_minutes > 0) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.appointments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference text UNIQUE NOT NULL DEFAULT ('SP-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  service_id bigint NOT NULL REFERENCES public.services(id),
  customer_name text NOT NULL CHECK (length(trim(customer_name)) BETWEEN 2 AND 120),
  customer_phone text NOT NULL CHECK (length(trim(customer_phone)) BETWEEN 7 AND 30),
  customer_email text CHECK (customer_email IS NULL OR position('@' in customer_email) > 1),
  starts_at timestamptz NOT NULL,
  ends_at timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled', 'no_show')),
  customer_notes text,
  admin_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (ends_at > starts_at)
);
CREATE INDEX IF NOT EXISTS appointments_starts_status_idx ON public.appointments(starts_at, status);
CREATE INDEX IF NOT EXISTS appointments_user_idx ON public.appointments(user_id, starts_at DESC);

CREATE OR REPLACE FUNCTION public.create_salon_appointment(
  p_service_id bigint, p_user_id uuid, p_customer_name text, p_customer_phone text,
  p_customer_email text, p_starts_at timestamptz, p_customer_notes text DEFAULT null
) RETURNS public.appointments
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE selected_service public.services; created public.appointments; calculated_end timestamptz;
BEGIN
  SELECT * INTO selected_service FROM public.services WHERE id=p_service_id AND enabled=true AND published=true;
  IF NOT FOUND THEN RAISE EXCEPTION 'service_not_available'; END IF;
  calculated_end := p_starts_at + make_interval(mins => selected_service.duration_minutes);
  PERFORM pg_advisory_xact_lock(hashtextextended((p_starts_at AT TIME ZONE 'Europe/London')::date::text, 0));
  IF EXISTS (SELECT 1 FROM public.appointments WHERE status <> 'cancelled' AND starts_at < calculated_end + interval '15 minutes' AND ends_at + interval '15 minutes' > p_starts_at) THEN
    RAISE EXCEPTION 'appointment_slot_unavailable';
  END IF;
  INSERT INTO public.appointments(user_id,service_id,customer_name,customer_phone,customer_email,starts_at,ends_at,customer_notes)
  VALUES(p_user_id,p_service_id,trim(p_customer_name),trim(p_customer_phone),nullif(trim(p_customer_email),''),p_starts_at,calculated_end,nullif(trim(p_customer_notes),'')) RETURNING * INTO created;
  RETURN created;
END; $$;
REVOKE ALL ON FUNCTION public.create_salon_appointment(bigint,uuid,text,text,text,timestamptz,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_salon_appointment(bigint,uuid,text,text,text,timestamptz,text) TO service_role;

CREATE TABLE IF NOT EXISTS public.business_hours (
  weekday smallint PRIMARY KEY CHECK (weekday BETWEEN 0 AND 6),
  is_open boolean NOT NULL DEFAULT false,
  opens_at time,
  closes_at time,
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (NOT is_open OR (opens_at IS NOT NULL AND closes_at IS NOT NULL AND closes_at > opens_at))
);

CREATE TABLE IF NOT EXISTS public.blocked_dates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  starts_on date NOT NULL,
  ends_on date NOT NULL,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (ends_on >= starts_on)
);

CREATE TABLE IF NOT EXISTS public.gallery_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_path text UNIQUE NOT NULL CHECK (storage_path !~ '(^|/)\.\.(/|$)'),
  alt_text text NOT NULL CHECK (length(trim(alt_text)) > 0),
  caption text,
  sort_order integer NOT NULL DEFAULT 0,
  published boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.site_content (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  data jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(data) = 'object'),
  updated_by uuid REFERENCES auth.users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.admin_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  target_table text,
  target_id text,
  before_data jsonb,
  after_data jsonb,
  ip text,
  user_agent text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.admin_audit_logs ADD COLUMN IF NOT EXISTS actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public.admin_audit_logs ADD COLUMN IF NOT EXISTS entity_type text;
ALTER TABLE public.admin_audit_logs ADD COLUMN IF NOT EXISTS entity_id text;
ALTER TABLE public.admin_audit_logs ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE INDEX IF NOT EXISTS salon_admin_audit_created_idx ON public.admin_audit_logs(created_at DESC);

CREATE OR REPLACE FUNCTION public.salon_set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DO $$ DECLARE table_name text; BEGIN
  FOREACH table_name IN ARRAY ARRAY['profiles','admin_users','services','appointments','gallery_images','site_content'] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS salon_updated_at ON public.%I', table_name);
    EXECUTE format('CREATE TRIGGER salon_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.salon_set_updated_at()', table_name);
  END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.salon_create_profile()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN INSERT INTO public.profiles(id) VALUES (NEW.id) ON CONFLICT (id) DO NOTHING; RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS salon_auth_user_created ON auth.users;
CREATE TRIGGER salon_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.salon_create_profile();

CREATE OR REPLACE FUNCTION public.prevent_final_salon_admin_removal()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF OLD.is_active = true AND (TG_OP = 'DELETE' OR NEW.is_active = false) AND
     (SELECT count(*) FROM public.admin_users WHERE is_active = true) <= 1 THEN
    RAISE EXCEPTION 'cannot remove the final active admin';
  END IF;
  RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;
DROP TRIGGER IF EXISTS protect_final_salon_admin ON public.admin_users;
CREATE TRIGGER protect_final_salon_admin BEFORE UPDATE OR DELETE ON public.admin_users FOR EACH ROW EXECUTE FUNCTION public.prevent_final_salon_admin_removal();

INSERT INTO public.business_hours(weekday,is_open,opens_at,closes_at) VALUES
  (0,false,null,null),(1,true,'10:00','19:00'),(2,true,'10:00','19:00'),
  (3,true,'10:00','19:00'),(4,true,'10:00','19:00'),(5,true,'10:00','19:00'),(6,true,'10:00','18:00')
ON CONFLICT (weekday) DO NOTHING;
INSERT INTO public.site_content(id,data) VALUES (1,'{}'::jsonb) ON CONFLICT (id) DO NOTHING;
