-- Staff/scheduling foundation. Apply this entire file as one transaction.
-- Existing appointments keep their IDs, contacts, status and service duration.
begin;

-- Hold the lock until COMMIT so no booking can enter between preflight and
-- exclusion installation. Run during a quiet window: this blocks booking writes.
lock table public.appointments in access exclusive mode;

do $$
declare overlap_count bigint; invalid_count bigint;
begin
  select count(*) into invalid_count from public.appointments
  where not isfinite(starts_at) or not isfinite(ends_at) or ends_at <= starts_at;
  if invalid_count > 0 then
    raise exception 'booking_staff_foundation: % appointments have invalid timestamps; review before retrying', invalid_count;
  end if;

  -- All legacy rows will belong to one default staff member. Compare occupied
  -- ranges (including the historical 15-minute buffer), not only service time.
  select count(*) into overlap_count
  from public.appointments a join public.appointments b on a.id < b.id
  where a.status in ('pending','confirmed','completed')
    and b.status in ('pending','confirmed','completed')
    and a.starts_at < b.ends_at + interval '15 minutes'
    and b.starts_at < a.ends_at + interval '15 minutes';
  if overlap_count > 0 then
    raise exception 'booking_staff_foundation: % overlapping appointment pairs; no backfill performed', overlap_count
      using hint = 'Review conflicting appointments with the setup guide query. Resolve with the shop owner, then retry the whole migration.';
  end if;
end $$;

create extension if not exists btree_gist;

create table public.staff (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 120),
  display_name text not null check (length(trim(display_name)) between 1 and 120),
  bio text,
  colour_hex text not null default '#a98152' check (colour_hex ~ '^#[0-9a-fA-F]{6}$'),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index staff_active_sort_idx on public.staff(sort_order, id) where is_active;
create trigger salon_updated_at before update on public.staff
  for each row execute function public.salon_set_updated_at();

create table public.staff_services (
  staff_id bigint not null references public.staff(id) on delete cascade,
  service_id bigint not null references public.services(id),
  primary key (staff_id, service_id)
);
create index staff_services_service_idx on public.staff_services(service_id, staff_id);

create table public.staff_weekly_hours (
  staff_id bigint not null references public.staff(id) on delete cascade,
  weekday smallint not null check (weekday between 0 and 6),
  is_working boolean not null default false,
  starts_at time,
  ends_at time,
  primary key (staff_id, weekday),
  check (not is_working or (starts_at is not null and ends_at is not null and ends_at > starts_at)),
  check ((starts_at is null and ends_at is null) or
    (starts_at is not null and ends_at is not null and ends_at > starts_at))
);

create table public.staff_time_off (
  id bigint generated by default as identity primary key,
  staff_id bigint not null references public.staff(id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reason text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (isfinite(starts_at) and isfinite(ends_at) and ends_at > starts_at)
);
create index staff_time_off_staff_range_idx on public.staff_time_off
  using gist (staff_id, tstzrange(starts_at, ends_at, '[)'));
create index staff_time_off_created_by_idx on public.staff_time_off(created_by);

alter table public.appointments
  add column staff_id bigint references public.staff(id),
  add column buffer_minutes integer not null default 15 check (buffer_minutes between 0 and 120),
  add column occupied_until timestamptz,
  add column source text not null default 'web' check (source in ('web','account','admin')),
  add column confirmation_token_hash text,
  add column cancelled_at timestamptz,
  add column cancelled_by uuid references auth.users(id) on delete set null;

do $$
declare default_staff_id bigint;
begin
  insert into public.staff(name, display_name) values ('預設員工', 'SALON POKE 團隊')
    returning id into default_staff_id;
  insert into public.staff_services(staff_id, service_id)
    select default_staff_id, id from public.services where enabled;
  insert into public.staff_weekly_hours(staff_id, weekday, is_working, starts_at, ends_at)
    select default_staff_id, weekday, is_open, opens_at, closes_at from public.business_hours;
  update public.appointments
    set staff_id = default_staff_id,
        occupied_until = ends_at + make_interval(mins => buffer_minutes);
  -- Compatibility for legacy insert/RPC callers until the v2 commands always
  -- supply staff_id. Explicit NULL is rejected; this is never a collision bypass.
  execute format('alter table public.appointments alter column staff_id set default %L', default_staff_id);
end $$;

-- Derive the range end on *every* insert/update, including direct SQL and old
-- RPCs. A supplied shorter occupied_until can never evade the exclusion guard.
create function public.salon_set_appointment_occupancy()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
  new.occupied_until := new.ends_at + make_interval(mins => new.buffer_minutes);
  return new;
end $$;
revoke all on function public.salon_set_appointment_occupancy() from public, anon, authenticated;
grant execute on function public.salon_set_appointment_occupancy() to service_role;
create trigger salon_appointment_occupancy before insert or update on public.appointments
  for each row execute function public.salon_set_appointment_occupancy();

alter table public.appointments
  alter column staff_id set not null,
  alter column occupied_until set not null,
  add constraint appointments_occupied_until_valid check (
    isfinite(starts_at) and isfinite(ends_at) and isfinite(occupied_until)
    and occupied_until = ends_at + make_interval(mins => buffer_minutes)
  );

alter table public.appointments
  add constraint appointments_staff_occupied_excl
  exclude using gist (
    staff_id with =,
    tstzrange(starts_at, occupied_until, '[)') with &&
  ) where (status in ('pending','confirmed','completed'));
create index appointments_staff_starts_idx on public.appointments(staff_id, starts_at);
create index appointments_cancelled_by_idx on public.appointments(cancelled_by);

alter table public.staff enable row level security;
alter table public.staff_services enable row level security;
alter table public.staff_weekly_hours enable row level security;
alter table public.staff_time_off enable row level security;

create policy staff_public_active on public.staff for select to anon, authenticated using (is_active);
create policy staff_services_public_available on public.staff_services for select to anon, authenticated
  using (exists (select 1 from public.staff s where s.id = staff_id and s.is_active)
    and exists (select 1 from public.services s where s.id = service_id and s.enabled and s.published));
create policy staff_weekly_hours_public_active on public.staff_weekly_hours for select to anon, authenticated
  using (exists (select 1 from public.staff s where s.id = staff_id and s.is_active));
create policy staff_time_off_admin_read on public.staff_time_off for select to authenticated
  using ((select public.is_salon_admin()));

-- Undo any old-project automatic grants before adding the precise API surface.
-- Admin mutations use server routes that recheck admin_users, validate and audit.
-- Private staff.name is available only to those server routes, never public reads.
revoke all on public.staff, public.staff_services, public.staff_weekly_hours, public.staff_time_off
  from public, anon, authenticated, service_role;
grant select (id, display_name, bio, colour_hex, is_active, sort_order) on public.staff to anon, authenticated;
grant select on public.staff_services, public.staff_weekly_hours to anon, authenticated;
grant select on public.staff_time_off to authenticated;
grant select, insert, update, delete on public.staff, public.staff_services, public.staff_weekly_hours, public.staff_time_off
  to service_role;
revoke all on sequence public.staff_id_seq, public.staff_time_off_id_seq from public, anon, authenticated, service_role;
grant usage on sequence public.staff_id_seq, public.staff_time_off_id_seq to service_role;

commit;
